#!/bin/bash
#
if test $# -ne 1;
then
echo "kuidas kasutada:"
echo "$0 ja siis lisada arv, näiteks ./paarsus3"
else
jaak=$(($1 % 2))
if test $jaak -eq 0
then
echo "antud arv on paaris"
else
echo "antud arv on paaritu"
fi
fi
