#!/bin/bash
#
#skripti algus
echo -n "Sisesta ridade arv: "
read n
makePyramid()
{
#
for((i=1;i<=n;i++))
do
for((k=1;k<=n;k++))
do
echo -ne "";
done
for((j=1;j<=i;j++))
do
echo -ne "*";
done
#
echo;
done
}
makePyramid 5
#
